# To use:
#
#   $ mamba env create -f environment.yml
#   $ mamba activate rgpotpy
#
name: rgpotpy
channels:
  - conda-forge
dependencies:
  - compilers
  - meson
  - cmake
  - gfortran
  - pkg-config
  - clang
  - openblas
  # Pinned
  - eigen==3.4.0
  # Libraries
  - fmt
  - spdlog
  # Testing
  - gtest
  # Python
  - pdm
