[workspace]
authors = ["Rohit Goswami <rgoswami@ieee.org>"]
channels = ["conda-forge"]
name = "pypotlib"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
compilers = ">=1.11.0,<2"
meson = ">=1.10.0,<2"
cmake = ">=4.2.1,<5"
gfortran = ">=14.3.0,<14.4"
pkg-config = ">=0.29.2,<0.30"
clang = ">=21.1.8,<22"
openblas = ">=0.3.31,<0.4"
eigen = "==3.4.0"
spdlog = ">=1.17.0,<2"
pybind11 = ">=3.0.1,<4"
gtest = ">=1.17.0,<2"
pdm = ">=2.26.4,<3"
rocksdb = ">=10.9.1,<11"
xxhash = ">=0.8.3,<0.9"
pkgconf = ">=2.5.1,<3"
numpy = ">=2.4.1,<3"

[feature.with-ase.dependencies]
numpy = ">=2.4.1,<3"
ase = ">=3.27.0,<4"
cmcrameri = ">=1.9,<2"
matplotlib = ">=3.10.8,<4"
ipython = "*"
pytest = ">=9.0.2,<10"

[environments]
with-ase = {features = ["with-ase"]}
